# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.example

# Dependencies
fabric_api_version=0.156.0+26.2

# Cloth Config / AutoConfig / ModMenu versions (kompatybilne z Minecraft 26.2)
cloth_config_version=26.2.155+fabric
autoconfig_version=6.2.4
modmenu_version=10.0.1

# opcjonalnie, jeśli chcesz Kotlin:
# kotlin_version=1.9.10
